/**
 * Route registry for deny-by-default enforcement.
 * Every protected API route MUST be listed here with its required permission.
 * CI test asserts: no route without permission; registry matches actual routes.
 * See docs/ENDPOINT_AUTHZ_EVIDENCE.md.
 */
import { Permissions, type Permission } from './permissions';

export type RouteSpec = {
  method: 'GET' | 'POST' | 'PATCH' | 'PUT' | 'DELETE';
  path: string;
  permission: Permission;
};

export const routeRegistry: RouteSpec[] = [
  { method: 'GET', path: '/api/admin/users', permission: Permissions.ADMIN_MANAGE_USERS },
  { method: 'POST', path: '/api/admin/users', permission: Permissions.ADMIN_MANAGE_USERS },
  { method: 'PATCH', path: '/api/admin/users/:id', permission: Permissions.ADMIN_MANAGE_USERS },
  { method: 'GET', path: '/api/settings/brandbook', permission: Permissions.ADMIN_MANAGE_USERS },
  { method: 'PATCH', path: '/api/settings/brandbook', permission: Permissions.ADMIN_MANAGE_USERS },
  { method: 'GET', path: '/api/tmc/items', permission: Permissions.TMC_REQUEST_VIEW },
  { method: 'GET', path: '/api/tmc/lots', permission: Permissions.TMC_REQUEST_VIEW },
  { method: 'GET', path: '/api/tmc/requests', permission: Permissions.TMC_REQUEST_VIEW },
  { method: 'GET', path: '/api/inspection/cards', permission: Permissions.INSPECTION_VIEW },
  { method: 'GET', path: '/api/inspection/report', permission: Permissions.INSPECTION_VIEW },
  { method: 'GET', path: '/api/inspection/cards/:id', permission: Permissions.INSPECTION_VIEW },
  { method: 'GET', path: '/api/inspection/cards/:id/audit', permission: Permissions.INSPECTION_VIEW },
  { method: 'GET', path: '/api/inspection/cards/:id/evidence', permission: Permissions.INSPECTION_VIEW },
  { method: 'POST', path: '/api/inspection/evidence/verify', permission: Permissions.INSPECTION_VIEW },
  { method: 'POST', path: '/api/inspection/cards/:id/transition', permission: Permissions.INSPECTION_MANAGE },
  { method: 'POST', path: '/api/inspection/cards/:id/check-results', permission: Permissions.INSPECTION_MANAGE },
  { method: 'GET', path: '/api/files/list', permission: Permissions.FILES_LIST },
  { method: 'GET', path: '/api/ai-inbox', permission: Permissions.AI_INBOX_VIEW },
  { method: 'POST', path: '/api/files/upload', permission: Permissions.FILES_UPLOAD },
  { method: 'GET', path: '/api/workspace/status', permission: Permissions.WORKSPACE_READ },
  { method: 'POST', path: '/api/workspace/init', permission: Permissions.WORKSPACE_READ },
  { method: 'GET', path: '/api/ledger/verify', permission: Permissions.LEDGER_READ },
  { method: 'POST', path: '/api/ledger/append', permission: Permissions.LEDGER_APPEND },
  { method: 'GET', path: '/api/authz/verify', permission: Permissions.WORKSPACE_READ },
  { method: 'GET', path: '/api/system/verify', permission: Permissions.WORKSPACE_READ },
  { method: 'GET', path: '/api/system/health', permission: Permissions.WORKSPACE_READ },
  { method: 'GET', path: '/api/compliance/keys', permission: Permissions.COMPLIANCE_VIEW },
  { method: 'POST', path: '/api/compliance/keys/rotate', permission: Permissions.COMPLIANCE_MANAGE },
  { method: 'POST', path: '/api/compliance/keys/:keyId/revoke', permission: Permissions.COMPLIANCE_MANAGE },
  { method: 'GET', path: '/api/compliance/keys/audit', permission: Permissions.COMPLIANCE_VIEW },
  { method: 'GET', path: '/api/compliance/verify-stats', permission: Permissions.COMPLIANCE_VIEW },
  { method: 'GET', path: '/api/compliance/export', permission: Permissions.COMPLIANCE_VIEW },
  { method: 'GET', path: '/api/compliance/retention', permission: Permissions.COMPLIANCE_VIEW },
  { method: 'GET', path: '/api/compliance/keys/requests', permission: Permissions.COMPLIANCE_VIEW },
  { method: 'POST', path: '/api/compliance/keys/requests', permission: Permissions.COMPLIANCE_MANAGE },
  { method: 'POST', path: '/api/compliance/keys/requests/:id/approve', permission: Permissions.COMPLIANCE_MANAGE },
  { method: 'POST', path: '/api/compliance/keys/requests/:id/reject', permission: Permissions.COMPLIANCE_MANAGE },
  { method: 'POST', path: '/api/compliance/keys/requests/:id/execute', permission: Permissions.COMPLIANCE_MANAGE },
  { method: 'GET', path: '/api/compliance/snapshots', permission: Permissions.COMPLIANCE_VIEW },
  { method: 'GET', path: '/api/compliance/break-glass', permission: Permissions.COMPLIANCE_VIEW },
  { method: 'POST', path: '/api/compliance/break-glass', permission: Permissions.ADMIN_MANAGE_USERS },
  { method: 'GET', path: '/api/compliance/audit-pack', permission: Permissions.ADMIN_MANAGE_USERS },
  { method: 'POST', path: '/api/compliance/audit-pack', permission: Permissions.ADMIN_MANAGE_USERS },
  { method: 'GET', path: '/api/compliance/legal-holds', permission: Permissions.COMPLIANCE_VIEW },
  { method: 'POST', path: '/api/compliance/legal-holds', permission: Permissions.ADMIN_MANAGE_USERS },
  { method: 'GET', path: '/api/compliance/postmortems', permission: Permissions.COMPLIANCE_VIEW },
  { method: 'POST', path: '/api/compliance/postmortems', permission: Permissions.COMPLIANCE_MANAGE },
  { method: 'GET', path: '/api/compliance/anomalies', permission: Permissions.COMPLIANCE_VIEW },
  { method: 'POST', path: '/api/compliance/anomalies', permission: Permissions.COMPLIANCE_MANAGE },
  { method: 'GET', path: '/api/compliance/policies', permission: Permissions.COMPLIANCE_VIEW },
  { method: 'POST', path: '/api/compliance/policies', permission: Permissions.ADMIN_MANAGE_USERS },
  { method: 'GET', path: '/api/compliance/delegations', permission: Permissions.COMPLIANCE_VIEW },
  { method: 'POST', path: '/api/compliance/delegations', permission: Permissions.COMPLIANCE_MANAGE },
  { method: 'GET', path: '/api/compliance/org', permission: Permissions.COMPLIANCE_VIEW },
  { method: 'POST', path: '/api/compliance/org', permission: Permissions.ADMIN_MANAGE_USERS },
  { method: 'POST', path: '/api/agent/validate', permission: Permissions.FILES_LIST },
  { method: 'POST', path: '/api/documents/finance/payments/export', permission: Permissions.DOC_VIEW },
  { method: 'GET', path: '/api/templates/export', permission: Permissions.DOC_VIEW },
  { method: 'GET', path: '/api/hr/training', permission: Permissions.HR_VIEW },
  { method: 'POST', path: '/api/hr/training', permission: Permissions.HR_MANAGE },
  { method: 'GET', path: '/api/hr/exams', permission: Permissions.HR_VIEW },
  { method: 'POST', path: '/api/hr/exams', permission: Permissions.HR_MANAGE },
  { method: 'GET', path: '/api/hr/vacations', permission: Permissions.HR_VIEW },
  { method: 'POST', path: '/api/hr/vacations', permission: Permissions.HR_MANAGE },
  { method: 'PATCH', path: '/api/hr/vacations', permission: Permissions.HR_MANAGE },
  { method: 'GET', path: '/api/hr/templates', permission: Permissions.HR_VIEW },
  { method: 'GET', path: '/api/hr/timesheet', permission: Permissions.HR_VIEW },
  { method: 'POST', path: '/api/hr/timesheet', permission: Permissions.HR_MANAGE },
  { method: 'POST', path: '/api/documents/search', permission: Permissions.FILES_LIST },
  { method: 'POST', path: '/api/signature/idemia/create', permission: Permissions.LEDGER_APPEND },
  { method: 'POST', path: '/api/signature/idemia/consent', permission: Permissions.LEDGER_APPEND },
  { method: 'POST', path: '/api/signature/idemia/verify-portrait', permission: Permissions.LEDGER_APPEND },
  { method: 'POST', path: '/api/signature/idemia/capture-document', permission: Permissions.LEDGER_APPEND },
  { method: 'GET', path: '/api/signature/idemia/status', permission: Permissions.LEDGER_APPEND },
  { method: 'GET', path: '/api/signature/idemia/healthcheck', permission: Permissions.LEDGER_APPEND },
  { method: 'DELETE', path: '/api/signature/idemia/delete', permission: Permissions.LEDGER_APPEND },
];
